sudo: required

language: perl

perl:
  - "5.16"
  - "5.22"

addons:
  postgresql: "9.3"

env:
  global:
    - PGVERSION="9.3"
    - JANSSON_VERSION="2.7"
    - DNAP_UTILITIES_VERSION="0.5.1"
    - DNAP_WAREHOUSE_VERSION="2.1"
    - IRODS_WRAP_VERSION="2.4.0"
    - NPG_ML_WAREHOUSE_VERSION="39.0"
    - NPG_QC_VERSION="61.1"
    - NPG_SEQ_COMMON_VERSION="50.9"
    - NPG_TRACKING_VERSION="85.3"
    - BATON_VERSION="0.16.4"
    - SAMTOOLS_VERSION="1.3.1"
    - HTSLIB_VERSION="1.3.1"

before_install:
  - ./scripts/travis_before_install.sh

install:
  - ./scripts/travis_install.sh

before_script:
  - source ./scripts/travis_before_script.sh
  - ienv
  - ilsresc -l
  - ils

script:
  - ./scripts/travis_script.sh

after_script:
  - ./scripts/travis_after_script.sh
